export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const GET_DELIVERYBOOK_ERROR = 'GET_DELIVERYBOOK_ERROR';
export const GET_DELIVERYBOOK_SUCCESS = 'GET_DELIVERYBOOK_SUCCESS';
GET_DELIVERYBOOK_SUCCESS