export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_ERORR = 'GET_REGIONS_ERORR';
export const GET_REGIONS_LOADING = 'GET_REGIONS_LOADING'; 
export const SET_SELECTED = 'SET_SELECTED';